# JavaScript 异步解决方案

> ### 背景

​	早期 js 作为浏览器的脚本语言，主要是实现用户与浏览器之间的交互，以及操作 `dom`，这决定了它只能是 单线程，否则会带来更复杂的同步问题。
为了避免复杂性，从一诞生，js 就是 **单线程** 语言。

​	js 是`单线程`的，所有任务在`主线程`上执行，js 引擎中负责解释和执行 `JavaScript 代码` 的线程只有一个。
​	除主线程外，还有其他工作线程：处理 `ajax` 请求的线程、处理 `dom` 事件（`click，keyUp...`）的线程、定时器线（`setTimeout、setInterval`）程、文件读写（`nodejs`）线程等。

##### `同步与异步`

​	单线程模式的好处是实现起来比较简单，执行环境相对单纯，

​	但当一个任务执行过程比较长的时候，比如 文件读取/ajax请求，后面的任务需要等待的时间较长，可能会阻塞其他任务的执行，甚至导致卡死

​	`同步任务` 则是指那些没有被引擎挂起、在主线程上排队执行的任务，当前一个任务执行完毕，才能执行后一个任务。

​	`异步任务` 则不同，每一个任务有一个或多个回调函数，前一个任务结束后，并不是直接执行后一个任务，执行顺序与任务的排列顺序是不一致的、异步的。

​		异步任务不会直接进入主线程执行，而是将事件添加到任务队列（也叫消息队列），这是一个 FIFO 的数据结构，	
​		当同步任务执行完成并且主线程有空时，读取任务队列的异步任务，有哪些事件，排在前面的优先执行
​		如果指定了回调函数，就会执行回调函数的代码，也就是异步任务

​	`事件循环机制` 其实就是指：主线程的执行栈不断从任务队列里面读取任务，执行完成后栈被清空，继续读取任务



> ### 异步问题的解决方案

### 1. 回调函数（callback）

​	简单理解回调函数，就是一个函数被作为参数传递给另一个函数

​	回调函数并不一定就是异步，并没有直接关系，只不过回调函数是异步的一种解决方案。

如：

```js
ajax(url, () => {
    ajax(url, () => {
        ajax(url, () => {
            ajax(url, () => {
            })
        })
    })
})
```

上面的代码在传统 Ajax 请求中比较常见，比如业务上需要在一个请求后发起另一个请求

这种异步回调中，回调函数的执行栈与原函数分离开，外部无法抓住异常，异常会变得不可控

特点：

- 基本的异步处理方法，比较简单，容易实现

- 但容易出现回调函数嵌套，也就是所谓的 回调地狱

- 高耦合性

虽然回调函数有其缺点，但日常开发中也不可或缺，需注意使用

### 2. Promise

​	ES2015 (ES6) 标准化和引入了 `Promise` 对象，它是异步编程的一种解决方案

​	Promise 的 ***链式调用***将很好的解决***回调地狱*** : `promise().then().fetch()`

`简单使用`：

```js
new Promise((resolve, reject) => {
    axios
    .get('')
    .then(res => {
        resolve(res.data)
	})
    .catch(err => {
        reject(err)
	})
})
```



`promise` 是一个承诺，无论成功还是失败，都会在将来返回一个执行结果，

​	new 一个 promise，传入需要执行的异步函数，这个函数不需要关心结果，结果将由 promise 处理，

​	.then() 返回的是一个新的 promise，这个结果受 reject 、resolve 影响 resolve 可以将执行成功的结构返回



`三种状态`：pending(进行中) 、Resolved(已完成) 和 Rejected(已失败)

​	调用 `resolve` 方法，将会把状态从  pending 变为 resolve

​	调用 `reject` 方法，将会把状态从  pending 变为 reject



`其他方法`：

 1. `Promise.all([p1, p2])` 将多个Promise 实例包装成一个新的 Promise实例，当所有结果都为 `resolve` 时，才会将返回值传递给 all 的实例

    ```js
    let p1 = Promise.resolve(1)
    let p2 = Promise.resolve(2)
    let p3 = Promise.reject(3)
    
    let p = Promise.all([p1, p2, p3])
    
    p.then(data => {
      console.log(data)
    })
    ```

 2. `Promise.race([p1, p2])` 与 all 相反，只需一个实例结果为 resolve 则返回

    ```js
    const p1 = new Promise((resolve, reject) => {
      setTimeout(resolve, 1000, "1")
    })
    
    const p2 = new Promise((resolve, reject) => {
      setTimeout(resolve, 500, "2")
    })
    
    Promise.race([p1, p2])
      .then(value => {
        console.log(value) // 2
      })
    ```

 3. `Promise.finally()` ES2018 补充的方法，不管结果成功或者失败，都将执行 finally 回调

    ```js
    p.finally(function() {
      // 返回状态为(resolved 或 rejected)
    });
    ```

 4. `Promise.resolve()` 接收一个值，将现有对象转为 Promise 对象

 5. `Promise.reject()` 与 resolve 方法一样，不过是返回一个带有拒绝原因的 `Promise` 对象

 6. ...



`简单实现原生 Promise`

```js
class Promise () {
    constructor (excutor) {
        this.status = 'pending'
        this.value = undefined
        this.reason = undefined
        this.resolveCallback = []
        this.rejectCallback = []

        let resolve = (value) => {
            if (this.status === 'pending') {
                this.status = 'resolve'
                this.value = value
                this.resolveCallback.forEach(fn => fn())
            }
        }

        let reject = (reason) => {
            if (this.status === 'pending') {
                this.status = 'reject'
                this.reason = reason
                this.rejectCallback.forEach(fn => fn())
            }
        }

        excutor(resolve, reject)
    }

    then(onResolve, onReject) {
        if (this.status === 'resolve') {
            onResolve(this.value)
        }
        if (this.status === 'reject') {
            onReject(this.reason)
        }
        if (this.status === 'pending') {
            this.resolveCallback.push(() => {
                onResolve(this.value)
            })
            this.rejectCallback.push(() => {
                onReject(this.reason)
            })
        }
    }
}
```

### 3. Generator

​	Generator 是 ES6 提供的一种异步编程的解决方案，最大的特点就是能够控制函数的执行(`next()`启动 和`yield()`暂停)

1. 声明：
```js
function *fn() {}
function* fn() {}
```
2. yield 可暂停，next 方法可启动，每次返回的 `res.value` 都是 `yield` 后的结果

```js
function *main() {
    let x = yield 'starting'
    let y = yield (x * 2)
    
    return x + y
}

let it = main()
let res = it.next()         // 第一个 next() 用于启动生成器
console.log(res.value)      // starting

// 第二个 next() 传入参数 5，第一个 yield 后面的值 = 5
// 所以 main 函数中，let x = 5
// 第二个 yield 返回值 = 5*2 = res.value = 10

res = it.next(5)            // x 被赋值为 5
console.log(res.value)      // 10

res = it.next(20)           // y 被赋值为 20
console.log(res.value)      // 25
res = it.next()             // 未传值
console.log(res.value)      // undefined
```

> res.value = yield 后面的结果
>
> next(x) 传递的参数 x 是上一个 yield 后面的值

4. 封装异步操作：
```js
var fetch = require('node-fetch');
function* gen(){
  var url = 'https://api.github.com/users/github';
  var result = yield fetch(url);
  console.log(result.bio);
}

var g = gen();
var result = g.next();               // 是一个 promise 对象
result.value.then(function(data){
  return data.json();
}).then(function(data){
  g.next(data);
});
```

> next() 不能自动执行，必须手动调用，可以借助 co 库

### 4. async await

​	多个 promise 链并且后一个依赖于前一个的结果时，参数传递非常不便，async/await 解决	

​	`async` 用于声明一个 `function` 是异步的，`await` 用于等待一个异步方法执行完成

​	且 `await` 只能出现在 `async` 函数中

> async 在做什么

```js
async function fn() {
  return "this is async"
}
const res = fn()
console.log(res)
// Promise {<resolved>: "this is async"}
```

`async` 函数返回的是一个 Promise 对象，也可以用 `then` 链来处理这个 Promise 对象

```js
fn().then(res=>{
  console.log(res)
})
```

> await 在等待什么

按照语法说明， `await` 等待的是一个表达式，这个表达式的计算结果是 Promise 对象或者其它值

- `await` 后面不是Promise对象，直接执行
- `await` 后面是Promise对象会阻塞后面的代码，Promise对象 `resolve`，然后得到 `resolve` 的值，作为 `await` 表达式的运算结果
- `await` 只能在 `async` 函数中使用（`await` 会阻塞后面代码，如果直接使用 `await` 结果就如同同步阻塞）

> 处理异常

```js
const doRequest = () => {
  try {
    getJSON()
      .then(result => {
        // JSON.parse可能会出错
        const data = JSON.parse(result)
        console.log(data)
      })
      // 取消注释，处理异步代码的错误
      // .catch((err) => {
      //   console.log(err)
      // })
  } catch (err) {
    console.log(err)
  }
}
```

在上面的 promise 示例中，try/catch 不能处理 JSON.parse 的错误，因为它在 Promise 中。我们需要使用 `.catch`，这样错误处理代码非常冗余

而使用 aync/await 的话，catch 能处理 JSON.parse 错误

```js
async function fn () {
  try {
    let res = await ajax()
    console.log(res)
  } catch (err) {
    console.log(err)
  }
}
```

> 优越性

	1. 简洁，无需 `.then`，无需函数处理 resolve 的结果，也避免了嵌套
	1. 可读性
	1. 上述错误处理
	1. 调试简单，断点
	1. 并发请求



> ### 总结

​	对于常用的不同异步编程处理方案，针对不同的业务场景可根据情况选择合适高效的方案













